name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install NodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: npm install and build
      run: |
        npm ci
        npm run build

    - name: Lint Styles
      run: |
        npm run lint:css
